import os
import random
from functools import lru_cache

import cv2
import numpy as np
import torch
from easydict import EasyDict as edict
from torch.utils.data import DataLoader, Dataset


EXPECTED_FIELDS = 9

def _split_path(path):
    """Split both Windows and POSIX separators consistently."""
    return path.replace("\\", "/").split("/")


def _subject_from_image_path(path):
    parts = _split_path(path)
    if len(parts) < 2:
        return ""
    return parts[1].split("_")[0]


def _parse_pair(text, name):
    values = text.split(",")
    if len(values) != 2:
        raise ValueError(f"Invalid {name} field: {text!r}")
    try:
        return [float(values[0]), float(values[1])]
    except ValueError as exc:
        raise ValueError(f"Invalid numeric {name} field: {text!r}") from exc

def _parse_triplet(text, name):
    values = text.split(",")
    if len(values) != 3:
        raise ValueError(f"Invalid {name} field: {text!r}")
    try:
        return [float(values[0]), float(values[1]), float(values[2])]
    except ValueError as exc:
        raise ValueError(f"Invalid numeric {name} field: {text!r}") from exc

def Decode_LBW(line):
    anno = edict()
    parts = line.strip().split()

    if not parts:
        raise ValueError("Empty LBW label line")

    if len(parts) < EXPECTED_FIELDS:
        raise ValueError(
            "Invalid LBW label format: "
            f"expected >= {EXPECTED_FIELDS} fields, got {len(parts)}\n"
            f"Line: {line.strip()}"
        )

    anno.face = parts[0]    #facesave
    anno.gaze2d = _parse_pair(parts[1], "gaze2d")
    anno.gaze3d = _parse_triplet(parts[2], "gaze3d")
    anno.fgaze3d = _parse_triplet(parts[3], "fgaze3d")
    anno.gaze = _parse_pair(parts[4], "GazeYawPitch")     #fgaze2d
    anno.left2d = _parse_pair(parts[5], "left2d")
    anno.pface = parts[6]
    anno.pgaze = _parse_triplet(parts[7], "pgaze")
    anno.pgaze2d = _parse_pair(parts[8], "pgaze2d")

    return anno



# def Decode_MPII(line):
#     """Decode the corrected 13-column MPIIFaceGaze label."""
#     anno = edict()
#     parts = line.strip().split()
#
#     if not parts:
#         raise ValueError("Empty MPII label line")
#
#     if len(parts) < EXPECTED_FIELDS:
#         raise ValueError(
#             "Invalid MPII label format: "
#             f"expected >= {EXPECTED_FIELDS} fields, got {len(parts)}\n"
#             f"Line: {line.strip()}"
#         )
#
#     anno.face = parts[0]
#     anno.lefteye = parts[1]
#     anno.righteye = parts[2]
#     anno.grid = parts[3]
#     anno.origin = parts[4]
#     anno.whicheye = parts[5]
#
#     # IMPORTANT:
#     # field 7 is now the normalized gaze yaw/pitch generated by
#     # data_processing_mpii.py. It is NOT the original screen pixel point.
#     anno.gaze = _parse_pair(parts[6], "GazeYawPitch")
#
#     # field 8 remains head pose and is NOT used as gaze target.
#     anno.headrot = parts[7]
#     anno.headtrans = parts[8]
#     anno.ratio = parts[9]
#     anno.face_corner = parts[10]
#     anno.left_eye_corner = parts[11]
#     anno.right_eye_corner = parts[12]
#
#     return anno


class GazeDataset(Dataset):
    def __init__(
        self,
        data_cfg,
        decode_func=Decode_LBW,
        test_subject=None,
        mode="train",
    ):
        if mode not in ("train", "test"):
            raise ValueError("mode must be 'train' or 'test'")

        self.root = data_cfg.image
        self.decode = decode_func
        self.mode = mode
        self.test_subject = test_subject
        self.header = data_cfg.get("header", False)
        self.source = []

        label_paths = data_cfg.label
        if isinstance(label_paths, str):
            label_paths = [label_paths]

        #先读取所有行，再按每行的 image path 中的 Subject ID 过滤
        for label_path in label_paths:
            with open(label_path, "r", encoding="utf-8") as f:
                lines = f.readlines()

            if self.header and lines:
                lines = lines[1:]

            for line in lines:
                if not line.strip():
                    continue

                anno = self.decode(line)
                subject = _subject_from_image_path(anno.face)

                if mode == "train":
                    # LOPO training: hold out test_subject.
                    if test_subject is not None and subject == test_subject:
                        continue
                else:
                    # LOPO testing: use ONLY the held-out subject.
                    if test_subject is not None and subject != test_subject:
                        continue

                self.source.append(line)


        print(
            f"[Dataset] mode={self.mode}, "
            f"test_subject={self.test_subject}, "
            f"samples={len(self.source)}"
        )

        self.subject_indices = {}
        for i, line in enumerate(self.source):
            anno = self.decode(line)
            subject = _subject_from_image_path(anno.face)
            self.subject_indices.setdefault(subject, []).append(i)

        print("[Dataset] subjects:", list(self.subject_indices.keys()))

        if not self.source:
            raise ValueError(
                "Dataset contains 0 samples. "
                f"mode={self.mode}, test_subject={self.test_subject}"
            )

        self.reset_paired_indices()

    def __len__(self):
        return len(self.source)

    def _load_and_transform(self, path):
        # Labels may contain either slash style.
        normalized_path = path.replace("/", os.sep).replace("\\", os.sep)
        img_path = os.path.join(self.root, normalized_path)

        img = cv2.imread(img_path)
        if img is None:
            raise FileNotFoundError(img_path)

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # data_processing_mpii.py saves face crops at 224x224.
        img = cv2.resize(img, (224, 224), interpolation=cv2.INTER_LINEAR)
        img = img.astype(np.float32) / 255.0
        mean = np.array(
            [0.485, 0.456, 0.406],
            dtype=np.float32
        )

        std = np.array(
            [0.229, 0.224, 0.225],
            dtype=np.float32
        )

        img = (img - mean) / std

        img = torch.from_numpy(img.transpose(2, 0, 1).copy())
        return img

    @lru_cache(maxsize=512)
    def _cached_load(self, path):
        return self._load_and_transform(path)

    def __getitem__(self, index):
        line = self.source[index]
        anno = self.decode(line)

        face_img = self._cached_load(anno.face)
        gaze = torch.tensor(anno.gaze, dtype=torch.float32)

        paired_index = int(self.paired_indices[index])
        paired_line = self.source[paired_index]
        paired_anno = self.decode(paired_line)

        paired_img = self._cached_load(paired_anno.face)
        paired_gaze = torch.tensor(
            paired_anno.gaze,
            dtype=torch.float32,
        )

        return (
            face_img,
            paired_img,
            gaze,
            paired_gaze,
        )

    def reset_paired_indices(self):
        self.paired_indices = np.zeros(
            len(self.source),
            dtype=np.int64,
        )

        for subject, idxs in self.subject_indices.items():
            if not idxs:
                continue
            for idx in idxs:
                # Pair only within the same subject.
                self.paired_indices[idx] = random.choice(idxs)


def loader(
    source,
    batch_size,
    shuffle=True,
    num_workers=4,
    is_sampler=False,
    persistent_workers=False,
    prefetch_factor=2,
    pin_memory=True,
    test_subject=None,
    mode="train",
    drop_last=None,
):
    """
    Build the DataLoader.

    mode='train': all subjects except test_subject.
    mode='test' : only test_subject.
    """
    dataset = GazeDataset(
        source,
        test_subject=test_subject,
        mode=mode,
    )

    # Training defaults to the original drop_last=True; test keeps every sample.
    if drop_last is None:
        drop_last = (mode == "train")

    kwargs = {
        "batch_size": batch_size,
        "shuffle": shuffle if mode == "train" else False,
        "num_workers": num_workers,
        "drop_last": drop_last,
        "pin_memory": pin_memory,
    }

    if num_workers > 0:
        kwargs["persistent_workers"] = persistent_workers
        kwargs["prefetch_factor"] = prefetch_factor

    return DataLoader(dataset, **kwargs)
